/* ===== ORDER BOOK API + INVARIANTS ===== */
/*
* Goal:
    A deterministic, price-time priority FIFO limit order book for ONE symbol.
    - Price priority: best price matches first (highest bid, lowest ask).
    - Time priority: within a price level, earlier orders match before later ones.

* Terminology:
    - incoming / taker: the new order currently being processed; it can "take" liquidity.
    - resting / maker: an order already in the book; it "makes" liquidity.
    - L2 snapshot: aggregated size at each price level (price -> total qty).

* Complexity:
    - Place: O(log P + M) where P is the number of price levels, M is number of matched orders.
    - Cancel: O(1) avg to locate + O(1) to erase from list + O(log P) if removing empty level.
    - Amend: depends if priority is lost (remove + reinsert).

* Concurrency:
    This class is intentionally single-threaded (no internal locks).
*/

#pragma once

#include "types.h"

#include <cstdint>
#include <string>
#include <list>
#include <map>
#include <optional>
#include <unordered_map>
#include <vector>


namespace ob {

/* New order command.
    - 'symbol' is kept in the request so that a higher-level "router" can dispatch per-symbol books.
    - 'id' must be globally unique at least per symbol.
    - For market orders, 'price' is ignored (it's not meaningful); only qty matters.
    - For limit orders, 'price' must be valid (> 0).
*/
struct NewOrder {
    std::string symbol;                     // which instrument this order belongs to
    OrderId id{};                           // client/exchange-assigned order identifier
    Side side{Side::kBuy};                  // buy or sell
    OrderType type{OrderType::kLimit};      // limit or market
    PriceTicks price{};                     // only for limit!
    Qty qty{};                              // size in integer lots
};

/* Amend/replace command.
    - Price change => lose time priority (remove from FIFO, reinsert at back of new price level).
    - Qty increase at same price => lose time priority (treated like replace).
    - Qty decrease at same price => keep time priority (stay at same FIFO position).

    "std::optional" fields are to allow: price-only, qty-only, or both at once changes.
*/
struct AmendOrder {
    OrderId id{};
    std::optional<PriceTicks> new_price;
    std::optional<Qty> new_qty;
};

/* Result of placing a new order.
*    Fields are designed for API consumers and testing:
        - accepted: request validated + processed (not neccessarily filled).
        - fully_filled: incoming order ended with remaining_qty = 0.
        - resting: if a LIMIT order had leftover qty and was inserted into the book.
        - filled_qty: total qty executed immediately.
        - trades: executions generated by this action, in the order they occured.
        - error: human-readable error if accepted = false.
*/
struct PlaceResult {
    bool accepted{false};
    bool fully_filled{false};
    bool resting{false};
    Qty filled_qty{0};
    Qty remaining_qty{0};
    std::vector<Trade> trades;
    std::string error;
};

/* Result of canceling a resting order.
    If canceled = false, either the order did not exist (alredy filled/canceled/unknown)
    or it was never resting.
*/
struct CancelResult {
    bool canceled{false};
    Qty remaining_qty{0};
};

/* Result of amending a resting order.
    'trades' can be non-empty because an amendment may create a cross (e.g, move bid above ask)
    which should trigger immediate matching.
*/
struct AmendResult {
    bool amended{false};
    Qty remaining_qty{0};
    std::vector<Trade> trades;
    std::string error;
};

/* OrderBook for a single symbol.
* Price-time priority:
    - Best price first: lowest ask, highest bid.
    - FIFO inside each price level.

* Public methods:
    - Place: may match immediately and/or rest remainder (limit only).
    - Cancel: removes a resting order by id.
    - Amend: modifies price/qty with exchange-like priority rules.
    - GetL2: aggregated depth view (L2).
*/
class OrderBook final {
public:
    explicit OrderBook(std::string symbol);

    // Inserts a new order (limit/market). Returns trades + whether is rested.
    PlaceResult Place(const NewOrder& req);

    // Cancels an existing RESTING order. Cancelling a filled/unknown id is a no-op.
    CancelResult Cancel(OrderId id);

    // Amends an existing RESTING order. Semantics described in AmendOrder comment.
    AmendResult Amend(const AmendOrder& req);

    /* L2 snapshot:
     *  Aggregated quantities per price level.
     *  - bids sorted best->worst (descending prices)
     *  - asks sorted best->worst (ascending prices)
    */
    struct Snapshot {
        std::vector<Level> bids; // best -> worst
        std::vector<Level> asks; // best -> worst
    };
    // Returns up to 'depth' levels of L2 data from each side.
    Snapshot GetL2(std::size_t depth) const;

    std::optional<PriceTicks> BestBid() const;
    std::optional<PriceTicks> BestAsk() const;

    const std::string& Symbol() const noexcept { return symbol_; }

private:
    /* Internal order represantation (L3-level).
        'seq' is a strictly increasing sequence number assigned at acceptance time.
        It's useful for:
            - debugging / logging / replay
            - proving determinism in tests
    */
    struct Order {
        OrderId id{};
        Side side{Side::kBuy};
        PriceTicks price{};
        Qty qty{};
        std::uint64_t seq{}; // monotonic sequence for debug/determinism
    };

    /* One price level: FIFO queue of orders at the same price.
        std::list is used so that:
            - iterators remain valid when other orders are inserted/erased somewhere
            - erase by iterator is O(1) (for fast Cancel)

        Matching loop always comsumes from fifo.front() (oldest order).
    */
    struct PriceLevel {
        std::list<Order> fifo; // FIFO: front=oldest (highest prio), back=newest

        // O(number of orders at that price)
        Qty TotalQty() const {
            Qty sum = 0;
            for (const auto& o : fifo) sum += o.qty;
            return sum;
        }
    };

    /* Book represantation (price -> level).
        std::map gives:
            - O(log P) insert/erase for price levels (P = number of price levels)\
            - O(1) best price access via begin() iterator

        Ordering differs by side:
            - bids: highest price is best => std::greated
            - asks: lowest price is best => std::less
    */
    using BidBook = std::map<PriceTicks, PriceLevel, std::greater<PriceTicks>>;
    using AskBook = std::map<PriceTicks, PriceLevel, std::less<PriceTicks>>;

    /* Locator for fast cancel/amend by order id.
        Stores enough to remove an order in near O(1):
            - side + price to find the right map bucket
            - list iterator pointing directly at the order node

        WARNING: iterators must remain valid while the order is resting.
                 That's why std::list is used (stable iterators).
    */
    struct Locator {
        Side side{};
        PriceTicks price{};
        std::list<Order>::iterator it;
    };

    // Matching: repeatedly cross incoming with the opposite side best price level(s).
    // Mutates incoming.qty downwards and emits trades (taker= incoming, maker= resting).
    void MatchIncoming(Order& incoming, std::vector<Trade>& out_trades);

    // Returns next monotonic sequence number of accepted orders.
    std::uint64_t NextSeq() noexcept { return ++seq_; }

    // Checks if incoming price crosses the spread and can match immediately.
    // For buy: incoming.price >= best ask
    // For sell: incoming.price <= best bid
    bool CrossesSpread(const Order& incoming) const;

    // Inserts remaining limit order qty into the correct side at its price.
    // Also updates 'index_' with locator info.
    void Rest(Order&& order);

    // Removes a resting order by a previously looked-up locator.
    // Also cleans up empty price levels and 'index_'.
    void EraseByLocator(OrderId id, const Locator& loc);

private:
    std::string symbol_;
    std::uint64_t seq_{0}; // used to assign Order::seq

    BidBook bids_;
    AskBook asks_;

    // Primary key for order lookup (cancel/amend).
    // For every resting order, index_[id] must exist and point to a valid list iterator.
    std::unordered_map<OrderId, Locator> index_;
};

} // namespace ob
